#!/bin/bash
#Compile cws
reset
gcc \
	./include/cws.c \
	./include/types.c \
	./include/util/log.c \
	./include/util/cws_string.c \
	./include/util/input.c \
	./include/io/file.c \
	./include/io/filesystem.c \
	./include/math/matrix.c \
	./include/math/collision.c \
	./include/gfx/video.c \
	./include/gui/gui.c \
	./include/scene/scene.c \
	./include/main.c \
	-L /usr/local/lib/luajit5.1/debug \
	-lSDL2 -lSDL2_image -lSDL2_ttf -lGL -lGLEW -lassimp -lluajit-5.1 \
	-o ./bin/cwstest \
	-g \
	-rdynamic \
	-Wall \
	-ldl \
	-lm
	#-shared \
	#-o ./bin/libcws.so \
	#-fpic \
	